name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: bitartes/pr-agent@v1  # After publishing, use specific version like @v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          llm_provider: deepseek        # or 'openai'
          deepseek_key: ${{ secrets.DEEPSEEK_API_KEY }}
          # openai_key: ${{ secrets.OPENAI_API_KEY }}  # uncomment if using OpenAI
          # openai_model: gpt-4        # optional: customize model
