name: Reusable PR Review

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: true
      ANTHROPIC_API_KEY:
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Clone PR Agent
      uses: actions/checkout@v3
      with:
        repository: bitartes/pr-agent  # Replace with your actual username/repo
        path: pr-agent

    - name: Install dependencies
      working-directory: pr-agent
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PR Review
      working-directory: pr-agent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        python pr_agent.py
